version: "3"
services:
  ## API
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: local
    container_name: '${PROJECT_NAME}_api'
    volumes:
      - ./:/var/www/app
    networks:
        - laravel_app
    depends_on:
      - mysql
      - redis
    ports:
      - "8081:8080"

  ## Mysql
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
        - '33306:3306'
    container_name: '${PROJECT_NAME}_mysql'
    environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
        - 'data-mysql:/var/app/lib/mysql'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-authentication-plugin=mysql_native_password --innodb_ft_enable_stopword=off
    networks:
      - laravel_app
  ## Redis
  redis:
    image: redis:7.0.4
    container_name: '${PROJECT_NAME}_redis'
    ports:
      - "6389:6379"
    volumes:
      - data-redis:/data
    networks:
      - laravel_app

networks:
    laravel_app:
        driver: bridge
volumes:
    data-mysql:
        driver: local
    data-redis:
        driver: local
